@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 16 10:53:56 +0700 2019
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim test_zipi8_behav -key {Behavioral:sim_1:Functional:test_zipi8} -tclbatch test_zipi8.tcl -view D:/workspace/Vivado_2018.3/zcu104/zipi8_rtl/test_top_ram_behav.wcfg -view D:/workspace/Vivado_2018.3/zcu104/zipi8_rtl/test_zipi_vs_kcpsm6.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
