webtalk_init -webtalk_dir D:/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.sim/sim_1/behav/xsim/xsim.dir/test_top_ram_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May  9 01:04:23 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "608657b9-2f2f-4574-9e10-3d579a5d14c9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0535b584bdc04dea8eb6859666e31242" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "83165600 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.42_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13800_KB" -context "xsim\\usage"
webtalk_transmit -clientid 461550300 -regid "" -xml D:/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.sim/sim_1/behav/xsim/xsim.dir/test_top_ram_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.sim/sim_1/behav/xsim/xsim.dir/test_top_ram_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.sim/sim_1/behav/xsim/xsim.dir/test_top_ram_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
