# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/esi/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.srcs/sources_1/ip/program_memory/program_memory.xci
# IP: The module: 'program_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/esi/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.srcs/sources_1/ip/program_memory/program_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/esi/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.srcs/sources_1/ip/program_memory/program_memory.xci
# IP: The module: 'program_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/esi/workspace/Vivado_2018.3/zcu104/zipi8_rtl/zipi8_rtl.srcs/sources_1/ip/program_memory/program_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
